language: csharp
mono: none
dist: xenial
dotnet: 2.2.101
install:
  - dotnet restore kankilog
  - dotnet restore kankilog.tests
script:
  - dotnet build kankilog
  - dotnet build kankilog.tests
  - dotnet test kankilog.tests/kankilog.tests.csproj
  - dotnet test kankilog.tests/kankilog.tests.csproj /p:CollectCoverage=true